#!/usr/bin/python
# -*- coding: utf-8 -*-
 
# iram-get-devname - find device name of i-Ram
#
# Copyright (C) 2011 Homin Lee <homin.lee@suapapa.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

import os
import sys
import commands

iRamName = "GIGABYTE i-RAM"

def foundDevName(modelName):
    for c in "abcdefghijklmnopqrstuvwxyz":
        devPath = "/dev/sd%s"%c
        if os.path.exists(devPath):
            report = commands.getoutput('/sbin/hdparm -i %s'%devPath)
            for line in report.split('\n'):
                if line.strip().startswith("Model=") and modelName in line:
                    return devPath
    return None

iRamDevName = foundDevName(iRamName)
if not iRamDevName:
    sys.exit(-1)

print iRamDevName
sys.exit(0)

# vim: et sw=4 fenc=utf-8:
